site: Annabel Lee Portfolio

#url: annabel-lee.xyz
#baseurl: annabel-lee.xyz

collections:
  pages:
    output: true
    permalink: /:name
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "wider"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed
  load_paths:
    - _sass
  quiet_deps: true

plugins:
  - jekyll-sitemap
  - jekyll-figure

grid_alignments:
  - top
  - center
  - bottom